name: issue open

on:
  issues:
    types:
      - opened
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send Message to discord
        run: |
          curl -X POST \
          -H "Content-Type: application/json" \
          -d '{
            "username": "이슈봇",
            "embeds" : [
              {
                "title": "이슈 오픈: ${{ github.event.issue.title }}",
                "color": 1127128,
                "description": "${{ github.event.issue.html_url }}",
                "fields": [
                  {
                    "name": "넘버",
                    "value": "#${{ github.event.issue.number }}",
                    "inline": true
                  },
                  {
                    "name": "작성자",
                    "value": "${{ github.event.issue.user.login }}",
                    "inline": true
                  }
                ]
              }
            ]
          }'\ ${{ secrets.DISCORD_LINK }}
