name: Issue Open Notification

on:
  issues:
    types:
      - opened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_LINK }}
          DISCORD_USERNAME: 알림봇
          DISCORD_EMBEDS: |
            [
              {
                "title": "이슈 오픈: ${{ github.event.issue.title }}",
                "color": 1127128,
                "description": "${{ github.event.issue.html_url }}",
                "fields": [
                  {
                    "name": "넘버",
                    "value": "#${{ github.event.issue.number }}",
                    "inline": true
                  },
                  {
                    "name": "작성자",
                    "value": "${{ github.event.issue.user.login }}",
                    "inline": true
                  }
                ]
              }
            ]