name: issue open

on:
  issues:
    types:
      - opened
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_LINK }}
          DISCORD_USERNAME: 알림봇
          DISCORD_EMBEDS: ${{ vars.NOTIFICATION_TEMPLATE }}
