name: issue open

on:
  issues:
    types:
      - opened
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send Message to discord
        env:
          title : ${{ github.event.issue.title }}
          url : ${{ github.event.issue.html_url }}
          issue_number : ${{ github.event.issue.number }}
          author : ${{ github.event.issue.user.login }}
        run: |
          curl -X POST \
          -H "Content-Type: application/json" \
          -d '{
            "username": "이슈봇",
            "embeds" : [
              {
                "title": "이슈 오픈: $title",
                "color": 1127128,
                "description": "$url",
                "fields": [
                  {
                    "name": "넘버",
                    "value": "#$issue_number",
                    "inline": true
                  },
                  {
                    "name": "작성자",
                    "value": "$author",
                    "inline": true
                  }
                ]
              }
            ]
          }'\ ${{ secrets.DISCORD_LINK }}
