name: issue open

on:
  issues:
    types:
      - opened
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: tsickert/discord-webhook@v6.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_LINK }}
          username: 알림봇
          embeds: |
            [
              {
                "title": "이슈 오픈: ${{ github.event.issue.title }}",
                "color": 1127128,
                "description": "${{ github.event.issue.html_url }}",
                "fields": [
                  {
                    "name": "넘버",
                    "value": "#${{ github.event.issue.number }}",
                    "inline": true
                  },
                  {
                    "name": "작성자",
                    "value": "${{ github.event.issue.user.login }}",
                    "inline": true
                  }
                ]
              }
            ]
          
