name: issue open

on:
  issues:
    types:
      - opened
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Load Notification Template
        run: echo "NOTIFICATION_TEMPLATE=${{ secrets.NOTIFICATION_TEMPLATE }}" >> $GITHUB_ENV

      - uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_LINK }}
          DISCORD_USERNAME: 알림봇
          DISCORD_EMBEDS: ${{ env.NOTIFICATION_TEMPLATE }}
